package com.cabin.hondacustom;

import android.content.Context;
import java.util.*;

/** Localized presentation only. Protocol values and decoder mappings stay unchanged. */
final class FytText {
    private static final Map<String,Integer> LABELS;
    static {
        Map<String,Integer> labels=new HashMap<>();
        labels.put("Navigation directions",R.string.fyt_label_0);
        labels.put("Off",R.string.fyt_label_1);
        labels.put("On",R.string.fyt_label_2);
        labels.put("Warning messages",R.string.fyt_label_3);
        labels.put("Panel configuration",R.string.fyt_label_4);
        labels.put("Type 1",R.string.fyt_label_5);
        labels.put("Type 2",R.string.fyt_label_6);
        labels.put("Type 3",R.string.fyt_label_7);
        labels.put("Reverse tone",R.string.fyt_label_8);
        labels.put("Speed reminders",R.string.fyt_label_9);
        labels.put("Message reminders",R.string.fyt_label_10);
        labels.put("Idle-stop reminders",R.string.fyt_label_11);
        labels.put("Eco background lighting",R.string.fyt_label_12);
        labels.put("Traffic sign display",R.string.fyt_label_13);
        labels.put("Alarm volume",R.string.fyt_label_14);
        labels.put("High",R.string.fyt_label_15);
        labels.put("Medium",R.string.fyt_label_16);
        labels.put("Low",R.string.fyt_label_17);
        labels.put("Trip B reset condition",R.string.fyt_label_18);
        labels.put("Refuel",R.string.fyt_label_19);
        labels.put("Ignition off",R.string.fyt_label_20);
        labels.put("Manual",R.string.fyt_label_21);
        labels.put("Trip A reset condition",R.string.fyt_label_22);
        labels.put("Outside-temperature adjustment",R.string.fyt_label_23);
        labels.put("−3",R.string.fyt_label_24);
        labels.put("−2",R.string.fyt_label_25);
        labels.put("−1",R.string.fyt_label_26);
        labels.put("0",R.string.fyt_label_27);
        labels.put("+1",R.string.fyt_label_28);
        labels.put("+2",R.string.fyt_label_29);
        labels.put("+3",R.string.fyt_label_30);
        labels.put("Speed / distance units",R.string.fyt_label_31);
        labels.put("km/h · km",R.string.fyt_label_32);
        labels.put("mph · miles",R.string.fyt_label_33);
        labels.put("Tachometer display",R.string.fyt_label_34);
        labels.put("Tachometer setting (vendor option)",R.string.fyt_label_35);
        labels.put("Doors",R.string.fyt_label_36);
        labels.put("Walk-away lock",R.string.fyt_label_37);
        labels.put("Remote-lock acknowledgement",R.string.fyt_label_38);
        labels.put("Automatic relock time",R.string.fyt_label_39);
        labels.put("30 seconds",R.string.fyt_label_40);
        labels.put("60 seconds",R.string.fyt_label_41);
        labels.put("90 seconds",R.string.fyt_label_42);
        labels.put("Automatic door-lock condition",R.string.fyt_label_43);
        labels.put("Speed-linked",R.string.fyt_label_44);
        labels.put("Shift out of P",R.string.fyt_label_45);
        labels.put("Automatic door-unlock condition",R.string.fyt_label_46);
        labels.put("Shift into P",R.string.fyt_label_47);
        labels.put("Lighting",R.string.fyt_label_48);
        labels.put("Wiper/headlight linkage",R.string.fyt_label_49);
        labels.put("Automatic interior-light sensitivity",R.string.fyt_label_50);
        labels.put("Minimum",R.string.fyt_label_51);
        labels.put("Maximum",R.string.fyt_label_52);
        labels.put("Automatic headlight sensitivity",R.string.fyt_label_53);
        labels.put("Automatic headlight-off delay",R.string.fyt_label_54);
        labels.put("0 seconds",R.string.fyt_label_55);
        labels.put("15 seconds",R.string.fyt_label_56);
        labels.put("Interior-light dimming time",R.string.fyt_label_57);
        labels.put("Remote access",R.string.fyt_label_58);
        labels.put("Keyless-access buzzer",R.string.fyt_label_59);
        labels.put("Keyless-access exterior-light acknowledgement",R.string.fyt_label_60);
        labels.put("Keyless alarm volume (vendor wording)",R.string.fyt_label_61);
        labels.put("Close (vendor wording)",R.string.fyt_label_62);
        labels.put("Distant (vendor wording)",R.string.fyt_label_63);
        labels.put("Horn with remote start",R.string.fyt_label_64);
        labels.put("Driver assistance",R.string.fyt_label_65);
        labels.put("LKAS suspension tone",R.string.fyt_label_66);
        labels.put("ACC vehicle-ahead detection tone",R.string.fyt_label_67);
        labels.put("Lane-departure system behavior",R.string.fyt_label_68);
        labels.put("Middle",R.string.fyt_label_69);
        labels.put("Wide",R.string.fyt_label_70);
        labels.put("Warnings only",R.string.fyt_label_71);
        labels.put("Forward-collision warning distance",R.string.fyt_label_72);
        labels.put("Far",R.string.fyt_label_73);
        labels.put("Near",R.string.fyt_label_74);
        labels.put("Cameras",R.string.fyt_label_75);
        labels.put("LaneWatch with turn signal",R.string.fyt_label_76);
        labels.put("LaneWatch duration after turn signal",R.string.fyt_label_77);
        labels.put("2 seconds",R.string.fyt_label_78);
        labels.put("Rear-view dynamic reminder (vendor wording)",R.string.fyt_label_79);
        labels.put("Rise warning (vendor wording; meaning unresolved)",R.string.fyt_label_80);
        labels.put("Driver attention monitor",R.string.fyt_label_81);
        labels.put("Visual warning",R.string.fyt_label_82);
        labels.put("Tactile and visual warnings",R.string.fyt_label_83);
        labels.put("Seats",R.string.fyt_label_84);
        labels.put("Seat-position memory linkage",R.string.fyt_label_85);
        labels.put("Electronic preloaded seat-belt movement mode (vendor wording)",R.string.fyt_label_86);
        labels.put("SWITCH LOCK (vendor wording; meaning unresolved)",R.string.fyt_label_87);
        labels.put("Lane-departure prevention behavior",R.string.fyt_label_88);
        labels.put("Standard",R.string.fyt_label_89);
        labels.put("Delay",R.string.fyt_label_90);
        labels.put("Warning only",R.string.fyt_label_91);
        labels.put("Advance",R.string.fyt_label_92);
        labels.put("Mirrors and windows",R.string.fyt_label_93);
        labels.put("Mirror folding",R.string.fyt_label_94);
        labels.put("Automatic folding",R.string.fyt_label_95);
        labels.put("Remote window control",R.string.fyt_label_96);
        labels.put("Tailgate sensor",R.string.fyt_label_97);
        labels.put("Rear-seat reminder",R.string.fyt_label_98);
        labels.put("Straight-line driving assistance",R.string.fyt_label_99);
        labels.put("During cruise control",R.string.fyt_label_100);
        labels.put("Within specified speed range",R.string.fyt_label_101);
        labels.put("Overspeed warning deviation",R.string.fyt_label_102);
        labels.put("+0 km/h",R.string.fyt_label_103);
        labels.put("+5 km/h",R.string.fyt_label_104);
        labels.put("+10 km/h",R.string.fyt_label_105);
        labels.put("+15 km/h",R.string.fyt_label_106);
        labels.put("Blind-zone warning",R.string.fyt_label_107);
        labels.put("Visual and audible warning",R.string.fyt_label_108);
        labels.put("Panel",R.string.fyt_label_109);
        labels.put("−5",R.string.fyt_label_110);
        labels.put("−4",R.string.fyt_label_111);
        labels.put("+4",R.string.fyt_label_112);
        labels.put("+5",R.string.fyt_label_113);
        labels.put("Automatic high beam",R.string.fyt_label_114);
        labels.put("Key and remote unlock mode",R.string.fyt_label_115);
        labels.put("Driver door",R.string.fyt_label_116);
        labels.put("All doors",R.string.fyt_label_117);
        labels.put("All doors when driver door opens",R.string.fyt_label_118);
        labels.put("All doors when shifted into P",R.string.fyt_label_119);
        labels.put("All doors when ignition off",R.string.fyt_label_120);
        labels.put("Remote-start system",R.string.fyt_label_121);
        labels.put("Door unlock mode",R.string.fyt_label_122);
        labels.put("Lockout Preset (vendor wording; meaning unresolved)",R.string.fyt_label_123);
        labels.put("New-message notifications",R.string.fyt_label_124);
        labels.put("Voice alarm system volume (vendor wording)",R.string.fyt_label_125);
        labels.put("Energy-saving automatic start/stop (vendor wording)",R.string.fyt_label_126);
        labels.put("Electric tailgate remote-opening condition",R.string.fyt_label_127);
        labels.put("Any time",R.string.fyt_label_128);
        labels.put("After unlocking",R.string.fyt_label_129);
        labels.put("Electric tailgate external-handle opening",R.string.fyt_label_130);
        labels.put("Traffic-sign small icon (vendor wording)",R.string.fyt_label_131);
        labels.put("Turning-point guide sign (vendor wording)",R.string.fyt_label_132);
        labels.put("Traffic-sign recognition (vendor option 1)",R.string.fyt_label_133);
        labels.put("Traffic-sign recognition (vendor option 2)",R.string.fyt_label_134);
        labels.put("Static reversing guidelines",R.string.fyt_label_135);
        labels.put("Dynamic reversing guidelines",R.string.fyt_label_136);
        labels.put("Show camera after reversing",R.string.fyt_label_137);
        labels.put("Reversing parking-space width",R.string.fyt_label_138);
        labels.put("Narrow",R.string.fyt_label_139);
        labels.put("Rear multifunctional system (vendor wording)",R.string.fyt_label_140);
        labels.put("Reversing delay",R.string.fyt_label_141);
        labels.put("Automatic trunk opening (vendor wording)",R.string.fyt_label_142);
        labels.put("Entry/exit seat movement",R.string.fyt_label_143);
        labels.put("Key and remote unlock mode (vendor option)",R.string.fyt_label_144);
        labels.put("Fatigue-driving information",R.string.fyt_label_145);
        labels.put("AWD information",R.string.fyt_label_146);
        LABELS=Collections.unmodifiableMap(labels);
    }
    static String label(Context context,String source){
        Integer resource=LABELS.get(source);
        if(resource==null)throw new IllegalArgumentException("Unregistered FYT label: "+source);
        return context.getString(resource);
    }
    static String[] options(Context context,FytProtocol.Control control){
        String[] labels=new String[control.options.length];
        for(int i=0;i<labels.length;i++)labels[i]=label(context,control.options[i]);
        return labels;
    }
}
